databases:
  - name: my_site
    databaseName: my_site
    user: my_site
    plan: free

services:
  - type: web
    name: my_site
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand only available on paid instance types
    # preDeployCommand: "bundle exec rails db:migrate" 
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_site
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
