services:
  - type: web
    name: bold_river_web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand only available on paid instance types
    # preDeployCommand: "bundle exec rails db:migrate" 
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
